GET http://localhost:9025/api/cart
# Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0MTA1NTUzLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzM0MTA3MzUzLCJpYXQiOjE3MzQxMDU1NTMsImp0aSI6IjYzOTBjNzI2LTg1YzUtNDIwNC04MTkxLWZhOWIzMzIyMzg5YyIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.h5zlMVO-07cm2U53u6MbrQHtjJWXucBI_Sima3jQkJM5IkPogKPYGgXnBFZksFJfPEFTE8Nw1CTIfiG3nbnJ2niyOid6sCZa_D2aezWyZthq0dSn4gCWrm6VRrAU5FY2o3NAQrusFrDHNSrLiS_9TdYK90P8KMwd_LVoYuwlfju4E7z_7z0dioMy81y3OHow8Z6ga2pA36K2KszYS62Qa8HEu2UqrGj3cdAoPnYUNYvnguAwUFqVQH9GjIlx6KDCN_ad6YsXGEzaIvlIDoUFd4O4fp7awCGYBzegvu7qvGL8mA9GmAGQc01fBmunN53n-cFnrYLKM3WhCKrgZhD5GA
Content-Type: application/json
Cookie: anon_id=61fc1ac2-3c35-48e5-98f4-a2056ac97f21