# возвращает список товаров из категории "Action"
GET localhost:9015/api/catalog/get-by-category/Action
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0MTMxOTA3LCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzM0MTMzNzA3LCJpYXQiOjE3MzQxMzE5MDcsImp0aSI6ImYwOWZjM2YyLWVhZjctNGI3Mi05NmUwLWMyMGJmYThmYjI0NiIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.JeblxsRXmxVcIKeJ-hWBi-YqsA2yOxkr2_HCyahRnGhzWHTMTT_6proQyBke3RO758XLcVOxhrbZiTVrzB5LKzKdWjSZ2C_nhMdt0w_R7FSk9DKwSJ3yic9cnVClG01EAtwfFxPPh920mt2gToLmLbslW9XL49wtQcQPqTtMHoGuDesiXFA3hG8gWh7jKogwgBYeLeUAx8ePdTVAJN6XPc3kAWXFyaeBbRPjGSwz0bbyTgCsIVca-Puwx3zNw6qNhPLHbOcea3OpyohXQblVPl4FW0QGG22HjDo3ImYXhJoiZNtdCowzPVJZ1oXdNRhsAwaVwHf0c68wU748WWebAQ
Content-Type: application/json
