# возвращает список всех товаров
GET localhost:9015/api/catalog/get-all
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0MTMxMDEzLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzM0MTMyODEzLCJpYXQiOjE3MzQxMzEwMTMsImp0aSI6IjZjZjRjYmQ0LTIzNmUtNDM0OC1hM2Y1LWE5NGFhYWRhYWFjNSIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.huD2--fIvqNzcOora0N9lSnHMkVdZ80rifKnbJ-J6Fx78v-aNlicxVNtS6vPKQMV2jc6fkxwH7LDbZGL8bJrDStV_7UOV_L5dqFh93zQnWVyMLq6Sj463BxmuyavFpYBcBIKTiXCNCH4gyz_zudHpvYibMZfE-ANPnCc3nz_Gpv4AdzS2n2ZoLMUzGYQm-KHvWz1hAx_5oZSEyb9xRPvhfTzcbXReLTxthJTX7cXcMmiojuVC2BNvX_dOwVIc5Xbh2PqLb6Juy4ApXUl6ZTPwCrHkYQumcOHwazK134-KB6qI2VD1YJrfGHhHlLauoSIHkmk1NjA3AVsabsWkzfGfA
Content-Type: application/json
