# возвращает список категорий
GET localhost:9015/api/catalog/get-categories
Authorization: Bearer eyJraWQiOiJmZmE4NjAzYi0zYTY2LTQzYmItODI1MS0wMDc1NTZhMzgzZGQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhcG1pZCIsImF1ZCI6ImFwbWlkIiwibmJmIjoxNzM0Mjg3MjcxLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDkwIiwiZXhwIjoxNzM0Mjg5MDcxLCJpYXQiOjE3MzQyODcyNzEsImp0aSI6IjdjOTc3NDZhLTY2YjItNGNjYi1iODg2LTk2OGE1N2RjMjgyMiIsImF1dGhvcml0aWVzIjpbIlJPTEVfU0VSVklDRSJdfQ.eT_v6ii-ux3hDyNpo1HPl0dDJjSbXzMxbwASTr2DB-bOf6U4CsewuGxyPzIqkQLlRo5m_CAzLoInTR1ZfohWMRzaCtZR8r-h4NTO3RGIFOiU1aBhVwd01vpo7jv72GREdrtfoCiV_FRNoQtfVgou1vhMA3uDSFMzFKyJU9t30kCRg1L30FS7d_rUHm8AkyfF9kijx9N-EtUCb8fWrjDpEuqyHqh_kwWFYWeEGnCPQIJggg0DHCk4d6h6hM_DzVmdcQjUPd7qER4v1I71hfmME8ul4vx_FMZ2_y1_iPwLs1LeWIypryKhfZJGI5NvWE9jEMUvNyxzT4xvBPPzgpbHeQ
Content-Type: application/json
